# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1

FROM python:3.12.6-slim

# Install runtime dependencies
RUN pip install --no-cache-dir \
    httpx>=0.28.1 \
    mcp[cli]>=1.6.0

WORKDIR /app
# Copy application code
COPY main.py /app/main.py

# Entrypoint to start the MCP server
ENTRYPOINT ["python", "/app/main.py"]
